### ISSUE TITLE
TOML based Configuration

### ISSUE THREAD

**Issue by varbhat** [johanmalm/labwc#101]
I understand that labwc follows Openbox when it comes to theming and configuration and thus has adopted XML.

But, XML has these flaws namely:
1) Difficult to Read
2) Too Verbose
3) Hard to modify manually
4) complex

Thus, i propose that labwc must adopt JSON (or TOML or other good configuration format) **ALONG WITH** currently used XML.

**Comment by johanmalm** [comment]
Hi there. Thanks for writing.

I agree that XML is quite ugly, but so are most config formats. I'd certainly put JSON in the ugly camp. TOML looks okay; I wasn't aware of it. Does it have a reliable C library to support it?

Changing the config format is pretty low priority for me. I'd much rather spend my time improving stability and completing the Cat A items in the Acceptance Criteria. I chose the Openbox syntax to avoid having to spend time re-inventing a spec.

I really don't see the point in supporting two config formats? Just seems like spending more time doing the boring bit of writing a compositor, and would add complexity, effort and dependencies.

**Comment by varbhat** [comment]
@johanmalm ,

We have https://github.com/cktan/tomlc99 to parse TOML in C.

Regarding priority , I agree with you . But, I think this belongs to low priority group and can be done in future?

If Supporting two config formats, can't openbox config file be converted to TOML first,then maybe used with labwc?

**Comment by johanmalm** [comment]
I don't think there is an overall argument to switch to TOML.

How would you handle menus?

**Comment by varbhat** [comment]
@johanmalm ,

Maybe inline tables ?(https://learnxinyminutes.com/docs/toml/)

I am not arguing for TOML tbh, more specifically i am arguing against XML for long term.

**Comment by johanmalm** [comment]
I think this belongs in a different project as follows:

- Develop labwc until it's production quality and all cat A items of CA are complete
- Refactor code-base into a stacking wlstem (or similar) library with a small client to deal with theme + config syntax.
- Create new projects with different config / theme syntax.

It might be worth considering unix sockets + protocols for this too. Just a thought. Will close this now.

**Comment by redtide** [comment]
FWIW I hope openbox XML configuration specification will never be replaced; I'm using openbox in X11 and I would like to make a (Qt) generic configuration tool that works also with labwc.

**Comment by varbhat** [comment]
@redtide , @johanmalm 
I don't want labwc to "replace" old XML configuration specification which is not much readable.
But, i want labwc to additionally support human readable/writable easy configuration format. configuration format must be easy to write/modify. for example, swaywm/i3 configuration format is very easy to write than say XML.

i know that it is not high priority (i want the team to focus on main parts of labwc and core problems ) but eventually i would like them to support easy to read/write configuration format.

also see:
1. https://git.sr.ht/~emersion/scfg
2. http://harmful.cat-v.org/software/xml/

@johanmalm , i think scfg can be good contender.

**Comment by redtide** [comment]
Sorry, I gave a too quick look on this before write an issue and I missed your "ALONG WITH currently used XML".

**Comment by johanmalm** [comment]
> FWIW I hope openbox XML configuration specification will never be replaced; I'm using openbox in X11 and I would like to make a (Qt) generic configuration tool that works also with labwc.

Sounds interesting.

Here is a GTK3 one (very minimal)

https://github.com/labwc/labwc-tweaks

**Comment by johanmalm** [comment]
> @redtide , @johanmalm I don't want labwc to "replace" old XML configuration specification which is not much readable. But, i want labwc to additionally support human readable/writable easy configuration format. configuration format must be easy to write/modify. for example, swaywm/i3 configuration format is very easy to write than say XML.
> 
> i know that it is not high priority (i want the team to focus on main parts of labwc and core problems ) but eventually i would like them to support easy to read/write configuration format.
> 
> also see:
> 
> 1. https://git.sr.ht/~emersion/scfg
> 2. http://harmful.cat-v.org/software/xml/
> 
> @johanmalm , i think scfg can be good contender.

Might a scfg2xml coverter be a good starting point? 
Reconfigure takes place on SIGHUP, so would be easy to write a wrapper script to do the conversion first

**Comment by acoolstraw** [comment]
Disagree with scfg, it looks like a weird blend of JSON and YAML. TOML looks a lot more readable.

**Comment by varbhat** [comment]
@johanmalm ,
I do have one big question. If i add Lua integration to labwc which can be enabled/disabled by compile flag,will it be accepted?

1) it can replace xml configuration for those who don't want it.


2) rule based filtering/ programming. if i wanted chromium to behave differently or perform some actions, i will be able to do it(recently chromium has started using shortcut inhibitor protocol which messes with system and having action can disable it for certain window)

one advantage on adding lua integration imo is that you can create plugins/extend the compositor. like adding tiling behaviour becomes easy
