### ISSUE TITLE
Auto-Hide-able Dock

### ISSUE THREAD

**Issue by varbhat** [johanmalm/labwc#102]
I know that this is not probably good place to ask this question but it's somewhat related.

When i was using fluxbox(cousin of openbox) , i used to use tint2 as dock. It could auto-hide and show only when cursor is hovered over bottom-center part of screen. I guess that it might have been single-horizontal-line when not hovered and dock when hovered over.

Now, how can i get similar dock(similar setup) in labwc? is it fundamentally not possible in wayland?

i know that other wlroots based compositor wayfire has custom protocol for this ( [wayfire-shell-unstable-v2](https://github.com/WayfireWM/wayfire/blob/master/proto/wayfire-shell-unstable-v2.xml) ). So, what's your stance on this? and how such functionalities can be implemented in labwc ?

**Comment by johanmalm** [comment]
Not sure.

I suspect the simplest method would be for a layer-shell bar to just change its size in response to the cursor position.

labwc supports layer-shell clients.

**Comment by varbhat** [comment]
Ok. But, such clients don't exist yet. It would be helpful to have them in future, I think.
