### ISSUE TITLE
request for window zoom and window transparency

### ISSUE THREAD

**Issue by droc12345** [johanmalm/labwc#106]
There are 2 features that I've gotten used to in wayfire, 
one is a window zoom (mouse scroll + some modifier) and 
the other is changing transparency of a window (mouse scroll + some modifier).

I'm not sure if it's possible using one or more of the protocols, or if you're even interested in doing that, so I thought I'd ask.

I know in openbox things like that would be done by something like tint2 or another standalone program, but wayland is different than X. 

Thanks for any help in this area.

**Comment by johanmalm** [comment]
Hi. Thanks for asking.

I'm trying to prevent scope creep, so unless features are Cat A in the Acceptance Criteria or there is a very good reason, I don't want to implement.

**Comment by droc12345** [comment]
I didn't think you'd want to do that at this stage, but I thought I'd ask. 
I'll probably look into it on my own to see how much work is involved in it.

I'll close this now.
Thanks
