### ISSUE TITLE
Example root-menu no longer works

### ISSUE THREAD

**Issue by jbeich** [johanmalm/labwc#109]
Bisected:
- ddf6555557d7 good
- b878db57a7c8 crashes (skipped)
- cd31283ba3d9 bad

`Web Browser` and `Terminal` defined in
https://github.com/johanmalm/labwc/blob/354161663e02ce85ca9ac075427c112054f6cfa8/docs/menu.xml#L6-L11
no longer appear. Instead the built-in entries from
https://github.com/johanmalm/labwc/blob/354161663e02ce85ca9ac075427c112054f6cfa8/src/menu/menu.c#L307-L316
appear due to the following error:
```
$ cp docs/*.xml ~/.config/labwc/
$ labwc
00:00:00.116 [../src/menu/menu.c:206] no menu with id 'root-menu'
00:00:00.123 [../src/config/session.c:109] no autostart file
^C
```

**Comment by johanmalm** [comment]
Fixed :smile:
Thanks for catching it.
