### ISSUE TITLE
Click dragging top/left/top-left corner causes jiggles

### ISSUE THREAD

**Issue by kelppo** [johanmalm/labwc#11]
As of https://github.com/johanmalm/labwc/commit/ca24c215eea64430a69fd870f4e9abc47d9f671e, click dragging top or left corner of a window causes jiggles on the opposite corner, click dragging top-left corner causes the entire window to jiggle.

**Comment by johanmalm** [comment]
Does it work if you build with the master branch of wlroots (in a 'subprojects' directory)

**Comment by kelppo** [comment]
Nope.

$ ldd /home/ketsui/labwc/build/labwc | grep wlroots  
libwlroots.so.7 => /home/ketsui/labwc/build/subprojects/wlroots/libwlroots.so.7 (0x00007f22aad75000)

**Comment by johanmalm** [comment]
Which commit actually changes the behaviour? 
The one labelled “Resize via dragging corners”?
Or has it always been like it?

**Comment by kelppo** [comment]
I tested 0347e5d9032be79c6318a0efff5c14be5e146995 (the one before "Resize via dragging corners") and click dragging the top or left border causes jiggling on the opposite side.

**Comment by johanmalm** [comment]
Thanks. I’ll take a look to see if I can figure it out.

**Comment by johanmalm** [comment]
That should be it
