### ISSUE TITLE
Grab openbox rc.xml file if it exists.

### ISSUE THREAD

**Issue by FlaviusHouk** [johanmalm/labwc#14]
If this compositor is influenced by openbox and even migh works with it's config, should labwc take openbox config if there is one? For example there might be additional entry in config_dirs array (dir.c, line 21) after labwc entry. If there is special entry, for labwc take it, if no - al least check available openbox one.

**Comment by johanmalm** [comment]
I prefer not to. 

Early commits did indeed respect the .config/openbox/rc.xml and XDG config dir equivalents, but I found it got confusing and prefer to keep it simple and explicit. 

Also, autostart and environment are likely to be pretty different from those used under X11 and will need to be handcrafted, so to use an rc.xml in a different directory is probably not all that helpful.

Hope that’s okay.

**Comment by FlaviusHouk** [comment]
Just would like to verify that this is an intended behavior.

**Comment by johanmalm** [comment]
Thanks
