### ISSUE TITLE
Stutter/hang with kitty+nano

### ISSUE THREAD

**Issue by everonline** [johanmalm/labwc#15]
Hi,

Building on Ubuntu 20.04, error on:

`[244/266] Compiling C object labwc.p/src_seat.c.o
../src/seat.c: In function ‘seat_focus_surface’:
../src/seat.c:128:3: warning: implicit declaration of function ‘wlr_seat_keyboard_notify_clear_focus’; did you mean ‘wlr_seat_keyboard_clear_focus’? [-Wimplicit-function-declaration]
  128 |   wlr_seat_keyboard_notify_clear_focus(seat->seat);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   wlr_seat_keyboard_clear_focus
[266/266] Linking target labwc
FAILED: labwc`

Changing seat.c to wlr_seat_keyboard_clear_focus made the build go through.

**Comment by johanmalm** [comment]
The wlroots API changes between releases, so you currently have to use wlroots 0.11.0 or 0.12.0 for a clean build.

```
git clone https://github.com/johanmalm/labwc
cd labwc
git clone https://github.com/swaywm/wlroots subprojects/wlroots
cd subprojects/wlroots && git checkout 0.12.0 && cd ../..
meson build
ninja -C build
```

**Comment by everonline** [comment]
Make sense. Thanks for the info.

**Comment by johanmalm** [comment]
Thanks.
I updated the wiki too. It said there to checkout 0.10.0, so that wasn't very helpful.

**Comment by everonline** [comment]
> Thanks. I updated the wiki too. It said there to checkout 0.10.0, so that wasn't very helpful.
> […](#)
> On 1 Feb 2021, at 18:16, everonline ***@***.***> wrote: ﻿ Make sense. Thanks for the info. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks but after going through it for a successful build you need an updated version from meson:

```
|Executing subproject wlroots method meson
|
|
|subprojects/wlroots/meson.build:1:0: Exception: Meson version is 0.53.2 but project requires >=0.54.0
```

You can grab it from groovy and it will go through:

> apt install ./meson_0.55.3-1_all.deb

Really like what you have here! Yet I saw some stutter / hang, for example when starting or when pushing nano through kitty, don't think its virtual box related since sway works fine.

It would be awesome if labwc gets mainstream, dont like Gnome and dislike tiling (sway) as well. For wayland only this 2 are considered stable.

**Comment by everonline** [comment]
PS: also create a deb package for it (in attach), did it quickly (didn't add the dependencies) so if anyone wants to use it on 20.04 or 20.10:

> apt install libwlroots6 (on groovy)
> apt install ./labwc_20210203-1_amd64.deb

[labwc_20210203-1_amd64.zip](https://github.com/johanmalm/labwc/files/5921033/labwc_20210203-1_amd64.zip)

**Comment by johanmalm** [comment]
> I saw some stutter / hang, for example when starting or when pushing nano through kitty, don't think its virtual box related since sway works fine.

I can't replicate this with kitty + nano. Could you try again with the current master branch.
Would you be able to build more context around what you were doing at the time of the hang/stutter. Are you able to consistently reproduce it? Is there something in particular that triggers it - e.g. using a keybind or moving a window with the mouse.

**Comment by everonline** [comment]
Hi Johanmalm,

The tests I did were under virtualbox with 2 cores and 1024 of RAM under Ubuntu 20.04 (created another deb package yesterday from Master) which normally is enough for a spin under terminal or a light window manager, that said the freeze comes from libinput that says my system is too slow:

![libinput](https://user-images.githubusercontent.com/47302125/108001888-a61c5280-6fe5-11eb-84c5-66c0380eca43.PNG)

So while I think is not since I run sway or openbox with the same resources with no problems (read it no freeze), probably some optimization is needed.

That being said and without trying to get out of topic if you pretend to go main stream a discussion menu would be great, not everything is a problem :), I was trying to use labwc as my main window manager (gnome hurt my eyes and trying to put sway as floating is like fighting its main purpose) but the only way I found to change the menu was actually on menu.c and compile everything back again (this was also the way I found you use sakura) and setting the resolution I had to grab the output and setting it on grub.

Do you have any other way or can you share your *.xml, not being able to add to the menu (seamlessly) is such a deal breaker.

I know is easy to ask but see it as suggestions.

Thanks

**Comment by johanmalm** [comment]
> probably some optimization is needed.

I've implemented damage-tracking which has significantly reduced CPU usage. Some optimisation still to do, but should work fine.

> the only way I found to change the menu was actually on menu.c and compile everything back again

We now support ~/.config/labwc/menu.xml - albeit it's a pretty simple implementation which only draws the root-menu (so, no submenus, separators or titles).

**Comment by johanmalm** [comment]
Will close this now before we go too far off-topic :smile:
