### ISSUE TITLE
E: missing-call-to-setgroups-before-setuid /usr/bin/labwc

### ISSUE THREAD

**Issue by tim77** [johanmalm/labwc#22]
Hello. I am trying to package `labwc` for Fedora and linter complaining about:

```
E: missing-call-to-setgroups-before-setuid /usr/bin/labwc
```

Here is similar issue and example of this could been fixed https://github.com/lxc/lxd/commit/616c9ce14f134bd7f47cd5a653b6d3d3d4d624e1.
Maybe we also can make our linters happier and fix this errors.

**Comment by jbeich** [comment]
`drop_permissions()` in labwc matches sway/wayfire/cage, neither of which call `setgroups`. Maybe fix in sway first as it has CI for Alpine+FreeBSD and more potential reviewers. For example, FreeBSD has `setgroups` in `<unistd.h>` rather than `<grp.h>`.

**Comment by tim77** [comment]
Thanks, you right. Sway also have this issue:
```
❯ rpmlint sway-1.5.1-2.fc34.x86_64.rpm                                
sway.x86_64: W: summary-not-capitalized C i3-compatible window manager for Wayland
sway.x86_64: E: missing-call-to-setgroups-before-setuid /usr/bin/sway
sway.x86_64: W: no-manual-page-for-binary swaybar
1 packages and 0 specfiles checked; 1 errors, 2 warnings.
```

**Comment by johanmalm** [comment]
Thanks both. @tim77 are you okay to reach out to the sway team? I’ll close this one for the minute.

**Comment by tim77** [comment]
Yep, i'll try to search first and then file a bug into Sway upstream. But no ETA because of free time.
