### ISSUE TITLE
[Feature Request] Snapping the Windows

### ISSUE THREAD

**Issue by varbhat** [johanmalm/labwc#24]
It would be nicer to have Snapping feature.

Snapping feature is when you drag windows to edge of the screen and window gets aligned to right side,left side, bottom side or fullscreen depending on edge.

It's present in KDE plasma, Wayfire, AwesomeWM , etc. 

I think that this feature will not bloat labwc .

**Comment by johanmalm** [comment]
Hi, yes this is part of the acceptance criteria. The acceptance criteria is currently work-in-progress on the wiki. I will add it to the labwc repo soon.

[http://openbox.org/wiki/Help:Configuration](http://openbox.org/wiki/Help:Configuration) specifies

```
<resistance>
  <strength>10</strength>
  <screen_edge_strength>20</screen_edge_strength>
</resistance>

strength Tells Openbox how much resistance (in pixels) there is between two windows before it lets them overlap.
screen_edge_strength Basically the same as strength but between window and the screen edge. 
```

**Comment by johanmalm** [comment]
Just for reference, it's now covered as AC 2.1.2
https://github.com/johanmalm/labwc/wiki/Acceptance-criteria
