### ISSUE TITLE
[Feature Request] Corner Hotspot

### ISSUE THREAD

**Issue by varbhat** [johanmalm/labwc#25]
My laptop's screen is limited , so i would like the running application to take full space in the screen.

Recommended Bar application for labwc is waybar. It is one of best bar for Wayland too. Unfortunately,it doesn't support Auto-Hide feature .
I have opened Issue here:

https://github.com/Alexays/Waybar/issues/1048#issue-827859104

Temporary solution for this is "hotspot" feature where the compositor executes a command when the cursor reaches designated corner of the screen.

**Comment by johanmalm** [comment]
I think this would be much better implemented via a client - consistent with labwc four aims.
