### ISSUE TITLE
Only border

### ISSUE THREAD

**Issue by hype3** [johanmalm/labwc#29]
Hi.

This is a feature I really want. Will it be possible in the future to just have a border around windows like sway, bspwm or any other tiling window managers? I really like the minimalistic of tiling window managers but not the tiling part of them.

Example:
The user can set the border width and color. Like 2px and orange will get a 2px and orange border around the windows.

**Comment by johanmalm** [comment]
Yes, 2.4.4 'keepBorder' should do this (not implemented yet)

**Comment by hype3** [comment]
Ahh didn't know that this was already implemented in Openbox. When I used Openbox longtime ago I used more normal theme settings. So how do I setup this? Should I use a empty theme and then enable borders?
Do I need to press ALT+LMousebutton to move windows and ALT+RMousebutton to rezise windows?

**Comment by johanmalm** [comment]
You can either select 'undecorate' from the client menu (alt-space by default I think).
Or in rc.xml you can set application specific behaviour

```
<applications>
  <application name="*">
    <decor>no</decor>
  <application>
<applications>
```

Or replace * with name/class/etc of your application.

Not sure if you can combine a meta-key with a mouse-bind in openbox. However, we're free to do whatever we want in labwc :smile:
In openbox, you can select move from the client menu - or just bind it a key-combination of mouse-event.

**Comment by johanmalm** [comment]
Need to sort out some fundamentals first though before we get too advanced with these things in labwc.
