### ISSUE TITLE
crashes on mouse click

### ISSUE THREAD

**Issue by zimbipw** [johanmalm/labwc#3]
labwc starts but as soon as I click with the mouse it crashes, here's the coredump
[labwc.txt](https://github.com/johanmalm/labwc/files/5356867/labwc.txt)

**Comment by johanmalm** [comment]
Have you done a git pull since last night?
Could you build with subprojects/wlroots and ASAN?
I’ll post command to use

**Comment by johanmalm** [comment]
From the project top-level directory (e.g. ~/src/labwc/)

```
git clone https://github.com/swaywm/wlroots subprojects/wlroots
meson -Db_sanitize=address,undefined build
ninja -C build
./build/labwc
```

If you then force the crash, we should get a more helpful stack-trace

**Comment by zimbipw** [comment]
On Fri, Oct 09, 2020 at 06:36:05PM +0000, Johan Malm wrote:
>Have you done a git pull since last night?
>Could you build with subprojects/wlroots and ASAN?
>I’ll post command to use
>
Ah,
did a new install from AUR and the issue is gone.

**Comment by johanmalm** [comment]
Good. Yes, I try to be ‘tidy’ with every commit, but forgot a couple of things  on Wed evening.
