### ISSUE TITLE
<command> expand tilde and variables

### ISSUE THREAD

**Issue by ekickx** [johanmalm/labwc#32]
Os: Fedora 34.20210423.n.0 (Silverblue)
labwc version: 0.2.0

It seems labwc can't execute bash script. Here is my [rc.xml](https://gist.github.com/ekickx/e8af98dd346087b6a4a8ca5a1f2a8fa3#file-rc-xml) and my [script](https://gist.github.com/ekickx/e8af98dd346087b6a4a8ca5a1f2a8fa3#file-volume). My script works well when I run it from terminal but somehow it can't run when I put in `<command>`

**Comment by johanmalm** [comment]
We use execvp()
This is consistent with openbox's approach and is safer than shell invocations.
In order to be consistent with openbox, we should expand tilde and variables for execvp() though. To be done :smile:

**Comment by ekickx** [comment]
Ohh ok. Thanks for the answer

**Comment by johanmalm** [comment]
I think this does it. Shout if it doesn't.

**Comment by ekickx** [comment]
It's work fine. Thank you
