### ISSUE TITLE
[Question] Display Manager

### ISSUE THREAD

**Issue by speltriao** [johanmalm/labwc#36]
I installed labwc  using the AUR. By default, my display manager (lightdm) doesn't show an option to labwc.

How can I login into labwc with lightdm? 

Thanks for the project.

**Comment by johanmalm** [comment]
Hi
I’ve not spent much time with Display Manager.
Do these instructions help?
https://github.com/johanmalm/labwc/wiki/Display-Manager

**Comment by speltriao** [comment]
Yep! That Works!

If I might make a suggestion, It would be nice to have a link to this wiki article on the ReadMe.

**Comment by johanmalm** [comment]
I've added a labwc.desktop file to the repository and included it in meson.build to be installed automatically.
