### ISSUE TITLE
Multi-monitor configs with a monitor above are unusable

### ISSUE THREAD

**Issue by cidkidnix** [johanmalm/labwc#39]
With a 4 monitor config, with 3 on the bottom row and 1 above it becomes unusable. Due to the fact that all other monitors have to have their y coord raised up by 1080 (in my case) and the top monitor placed at 0,0. All windows spawn at somewhere around 0,0 in my testing. Making this setup unusable since windows spawn off screen.

**Comment by johanmalm** [comment]
We now take into account output layout co-ordinates when positioning views on first map.
I had been meaning to center views on first map for a while, so have now implemented that too.
I'd be grateful to feedback to confirm it has worked on your setup.

**Comment by cidkidnix** [comment]
It isn't working for me for whatever reason, windows are still spawning at 0,0 (which is off screen for me)

**Comment by johanmalm** [comment]
Have you done a git pull to use the latest commit?

**Comment by cidkidnix** [comment]
Yes, I'm currently using nix and I've made 100% sure that the commit's have been pulled into the git build tree, the recent alt-button window drag changes have been applied and are usable

**Comment by johanmalm** [comment]
Okay, that's great.
I've tried setting up different screen combinations, including having the first one at (100,100) etc. It works for me, so not sure what's going on.
What application are you launching? Could you try with and xdg-shell application to start with.
If you just use one output without any kanshi or wlr-randr config, do the applications center?
What happens if you just use one screen with an offset? Does it pick up the layout co-ordinates?

**Comment by cidkidnix** [comment]
If it helps at all my current kanshi config is 
```
profile {
  output DP-2 mode 1920x1080@143.854996 position 1600,1080
  output HDMI-A-1 mode 1600x900 position 0,1080
  output DP-1     mode 1600x900 position 3520,1080
  output HDMI-A-2 mode 1920x1080 position 1600,0
}
```
and the windows still spawn off of screen, with all of the 1080's flipped to 0 and the 0 on HDMI-A-2 flipped to -1080 it centers on the current display but HDMI-A-2 becomes unusable for xwayland windows due to an xwayland bug with negative coords

**Comment by johanmalm** [comment]
I've pushed a few commit which might help.

If it's still not working, would you be able to re-produce the issue on a two-monitor setup? I haven't got four, so can't try your config.

**Comment by cidkidnix** [comment]
I'll test as soon as I can.

**Comment by johanmalm** [comment]
I have refactored quite a bit and think this has been resolved - I can't reproduce it anyway.
I'll shout for the time being, but do say if it's still a problem.
