### ISSUE TITLE
Maximised windows overlap waybar

### ISSUE THREAD

**Issue by nontntnt** [johanmalm/labwc#42]
Hi,

I am using labwc as compiled from the master in this repo. Using the latest version of waybar as available in Arch Linux.

When running waybar, and maximising a window, it covers waybar. The behaviour I would expect is that it would remain visible.

Am I getting something wrong? Is there anything I have missed?

Regards, a happy labwc user :)

**Comment by johanmalm** [comment]
As of commit a3ac2f2 last night, maximizing should now take into account the “usable area” and therefore stay clear of waybar.
Have you done a git pull in the last 18 hours?

**Comment by nontntnt** [comment]
You are very right. I compiled the very latest and it works perfectly well.

Thank you for your incredibly quick reply!

**Comment by johanmalm** [comment]
Thanks for letting me know - and glad your enjoying using it.
