### ISSUE TITLE
[Feature request] Drag to screen edge to tile

### ISSUE THREAD

**Issue by ghost** [johanmalm/labwc#43]
Would it be possible to implement basic drag to screen edge to tile functionality in labwc? Apologies if this is already possible and I have missed this!

For example: On window being dragged to the left side of the screen, the window gets automatically resized to 50% and left on the left side of the screen. 

If it's not possible to trigger this with the mouse, would it be possible to implement it with a key combo?

My proposal is only for left/right tiling, not necessarily anything more complex than that. 

If this can be implemented, it might be interesting to see how Wayfire does it, for example.

**Comment by johanmalm** [comment]
Yes, it'll be covered under the following:

http://openbox.org/wiki/Help:Configuration
1. <resistance><strength> and <resistance><screen_edge_strength>

http://openbox.org/wiki/Help:Actions
5.26 'MoveToEdge', 5.27 'GrowToEdge' and 5.28 'GrowToFill'

It's one of the things I'm missing myself, so it's quite high up on my list of things to do.

**Comment by nontntnt** [comment]
Awesome! Looking forward to it!

**Comment by johanmalm** [comment]
https://github.com/johanmalm/labwc/commit/49a73befdbf5b2ece788a37e98c8e6a5a23274ef
Not there yet, but this is a start.

**Comment by nontntnt** [comment]
Just tried that side of things. Working like a treat!

**Comment by johanmalm** [comment]
@Joshua-Ashton has just implemented a SnapToEdge action which does this and can be used with a keybind.

https://github.com/johanmalm/labwc/pull/76#issue-1028182472

In terms of triggering this with the mouse, I prefer to refactor cursor.c first and focus on implementing all the Cat A items in the acceptance criteria.

Will close for now.
