### ISSUE TITLE
[Question] How to get list of opened windows ?

### ISSUE THREAD

**Issue by ahmadraniri1994** [johanmalm/labwc#44]
I am not sure if it's a common question to be asked. I know on sway window manager, we can get list of opened windows with "swaymsg", though I never understand how it works. Can I do something like that on labwc ? I am arranging some stuffs to achieve something like "LXDE" on wayland. Labwc is the first thing on top list. Along with yambar as panel and other TUI tools as a proponent. Thanks. Once everything is complete, perhaps we can make something like "LWDE" (something like lxde but for wayland) :).

**Comment by johanmalm** [comment]
From about a week ago, labwc has simple support for the foreign-toplevel protocol, which lets you list open application and also maximize/minimize/etc applications.

https://github.com/swaywm/wlroots/blob/master/examples/foreign-toplevel.c is a simple client which you can try with labwc
Just run it without options to list applications. Run `foreign-toplevel -a <ID>` to maximize, and so on.

waybar supports the foreign-toplevel protocol and can be used like lxpanel/tint2/etc to show running application and maximize/minimize them. Towards the end of this video, you'll see me doing just that with waybar https://www.youtube.com/watch?v=AU_M3n_FS-E

I tried running yambar. It looks like it supports layer-shell, but not foreign-toplevel. 

I think swaymsg uses unix socket IPC. It's a nice way of controlling a compositor, but I decided to go the slightly simpler way of using a config file with a re-configure option whereby you have to assign actions to keybinds or mousebinds.

LWDE sounds nice :smile: The whole reason for creating a wlroots stacking compositor is to create that type of setup, so I'm definitely onboard. kwin and mutter are nice, but they are pretty big and very integrated with their respective stacks. I think that once you've got used to lightweight window managers/compositors, it's hard to go back to the giants.
