### ISSUE TITLE
[Question] Multiple keyboard layouts

### ISSUE THREAD

**Issue by geekydoc** [johanmalm/labwc#45]
Is it currently possible to have multiple keyboard layouts and cycle between them using a key combination? I believe swaywm supports that natively.

**Comment by johanmalm** [comment]
Use XKB_DEFAULT_OPTIONS.

For example, to use alt+shift to toggle between a Swedish & German layout, add the following to your `~/.config/labwc/environment`

```
XKB_DEFAULT_LAYOUT=se,de
XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle
```

See `man xkeyboard-config` for details.
