### ISSUE TITLE
Menu's font size (perhaps the font itself) is unchangable.

### ISSUE THREAD

**Issue by ahmadraniri1994** [johanmalm/labwc#46]
The latest master somehow makes menu's font size unchangable. I remembered the previous version have smaller menu font. I tried change it but no luck.
![menu-labwc](https://user-images.githubusercontent.com/72283174/129462695-46d326f7-4054-4373-9d5b-b2247f5c0758.png)

**Comment by johanmalm** [comment]
Thanks for feedback. Will sort.

**Comment by ahmadraniri1994** [comment]
Change with the Exact Name of font fix it. Thanks, I'll close it now. Thanks sir @johanmalm .
