### ISSUE TITLE
Unexpected behaviour with steam applications

### ISSUE THREAD

**Issue by hype3** [johanmalm/labwc#53]
Hi.

If I wan't to go fullscreen on youtube or any other movie window it only goes to fullscreen of the size of the actual window size. Not using the whole monitor. And if I click on fullscreen on window border it goes to fullscreen but with the border around the window.

It's the same in games if I go fullscreen I still see the border around the window.

**Comment by johanmalm** [comment]
Yep, will definitely implement this soon.

**Comment by hype3** [comment]
Now youtube / netflix works in fullscreen.
But in games when I do fullscreen there is something strange... where the titlebar was before in fullscreen there is now the background of my desktop instead. So it's like a invisible titlebar.

Also in some games where there is multiple windows on startup some of the windows is there but I can't click on them at all. The window is above everything else but everything under the window is getting all the focus. Like firefox labwc menu anything I tested is getting the focus but nothing on the window above.

**Comment by johanmalm** [comment]
Thanks for testing so quickly. I only checked with firefox, xterm and sakura, which was obviously not enough.
Could you suggest a game or application I could use to re-produce the issue?

**Comment by hype3** [comment]
I can't come up with any linux application right now that have some screen that is coming up sorry.
But all games that is for windows that uses proton on steam. When the steam play window is showing on the screen you cant close that one at all. I tested some games and it's the same with all of them. The other one that have the hidden titlebar is for linux on steam.
