### ISSUE TITLE
all output goes to stderr

### ISSUE THREAD

**Issue by ofiala-a51** [johanmalm/labwc#6]
labwc outputs everything to stderr, including `DEBUG` and `INFO` messages (when run with `-v` flag) and all messages from client programs run by labwc (which can obviously also include `INFO` and `DEBUG` messages if the programs are verbose).

This can be easily verified by running `$ labwc -vv 1> stdout.txt 2> stderr.txt` and examining the resulting files.

**Comment by johanmalm** [comment]
I’m happy with that.
Think it’s pretty normal behaviour.
INFO/ERROR/warn/etc are log messages, which I’m happy sending to stderr.
I guess labwc is unlikely to have regular output (which would normally be printed to stdout), so could get philosophical and argue “info” could go to stdout, but I’m not that philosophical 😄

**Comment by ofiala-a51** [comment]
`stderr` is not intended for log messages though, it's intended specifically for errors. Log messages belong into a logfile, although I realize the vast majority of GUI programs doesn't respect that...
