### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by nipsis** [johanmalm/labwc#64]
Build seems to fail with latest master. Is it just me?
Using up-to-date Arch Linux.

[289/312] Compiling C object labwc.p/src_xdg.c.o
FAILED: labwc.p/src_xdg.c.o
cc -Ilabwc.p -I. -I.. -Iinclude -I../include -Isubprojects/wlroots/include -I../subprojects/wlroots/include -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/libxml2 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -g -DWLR_USE_UNSTABLE -Wno-unused-parameter -Wundef '-DLABWC_VERSION="0.3.0-122-g6396608"' -pthread -MD -MQ labwc.p/src_xdg.c.o -MF labwc.p/src_xdg.c.o.d -o labwc.p/src_xdg.c.o -c ../src/xdg.c
../src/xdg.c: In function ‘handle_request_maximize’:
../src/xdg.c:137:54: error: ‘struct wlr_xdg_toplevel’ has no member named ‘client_pending’
  137 |                 view_maximize(view, surface->toplevel->client_pending.maximized);
      |                                                      ^~
[294/312] Compiling C object labwc.p/src_xwayland.c.o
ninja: build stopped: subcommand failed.

**Comment by Narrat** [comment]
In regards of the latest changes I assume your `wlroots-git` package isn't recent enough.
Please recreate a new wlroots-git package and then try again to build `labwc-git`

**Comment by johanmalm** [comment]
Thanks for reporting. Fix pushed.

**Comment by nipsis** [comment]
Thank you!
