### ISSUE TITLE
toggle maximize doesnt work

### ISSUE THREAD

**Issue by 7sarus** [johanmalm/labwc#66]
I have added "ToggleFullscreen" to my keybinds in rc.xml (ref:https://github.com/7sarus/dotfiles/commit/f54b3cd400049bb3737cd4e0c9319165310492e1)
But it doesn't seem to work. Toggle maximize works fine.  How do I get log or something of this to see if something is wrong on my end?

**Comment by johanmalm** [comment]
Is the /keybind in the wrong place?

https://github.com/7sarus/dotfiles/blob/f54b3cd400049bb3737cd4e0c9319165310492e1/labwc/rc.xml#L60

**Comment by 7sarus** [comment]
It was. My bad. Sorry for te trouble

**Comment by johanmalm** [comment]
Ha ha. No probs. Much prefer an easy issue.
