### ISSUE TITLE
labwc doesn't pass key shortcuts to child labwc

### ISSUE THREAD

**Issue by ofiala-a51** [johanmalm/labwc#7]
If labwc runs inside labwc, one would expect the keyboard shortcuts to be passed to the client when its window is active. However, that doesn't currently happen, which means that keyboard shortcuts cannot be used in the client. It can also catch the user by surprise if he expects to close an active window with labwc using Alt-Esc and it closes the parent instead.

**Comment by johanmalm** [comment]
Interesting. Hadn’t really thought about it.
Have a but busy couple of days ahead, but will investigate. How does sway behave in this respect?

**Comment by ofiala-a51** [comment]
It does the same... so I guess it's up to you whether labwc should behave more reasonably than sway in this case or not..

**Comment by johanmalm** [comment]
Okay. Will consider later.
