### ISSUE TITLE
Better support for notifications

### ISSUE THREAD

**Issue by Joshua-Ashton** [johanmalm/labwc#79]
Thunderbird notifications display in the center of the screen and get decorations. 

xeyes tells me it's a Wayland window and no XWayland too :thinking:

**Comment by johanmalm** [comment]
I've been able to reproduce.

The notifications must be WLR_XDG_SURFACE_TOP_LEVEL (https://github.com/johanmalm/labwc/blob/a67e74670b581a8abbd7542a3c41f97a721e89f1/src/xdg.c#L387)

And we center WLR_XDG_SURFACE_TOP_LEVEL surfaces which are not topmost (i.e. have a parent)
https://github.com/johanmalm/labwc/blob/a67e74670b581a8abbd7542a3c41f97a721e89f1/src/xdg.c#L285

Something obviously isn't quite right. Need to investigate.

I've not used Thunderbird for a long time, but it looks very GTK3ish, so am pretty sure it's Wayland. Also, the alt-tab dialog shows it's xdg-shell. Or did I misunderstand your xeyes note.

**Comment by Joshua-Ashton** [comment]
Yeah, I was not aware of it showing in alt-tab. Typically on other compositors, a good way of testing if Wayland vs XWayland is to use Xeyes. If the eyes move, the window is XWayland, if they stop, it's Wayland.

**Comment by ARDiDo** [comment]
It could possibly be because we aren't handling the toplevel's set_parent event. However, if this problem doesn't occur in Sway, then that isn't likely to be the case. Sway doesn't handle set_parent events either. 
Not sure how useful this may be, but this makes me think of Sevz17/dwl@57f4d64. In that case, a client's parent was found using their process ids.

**Comment by Joshua-Ashton** [comment]
The notifications should appear without ssd and in the bottom right corner of the screen. They shouldnt be parented I think. This works in plasma and gnome wayland

**Comment by Joshua-Ashton** [comment]
Tested it, and it does use a native notifications thing on KDE, yeah. Thanks for the tip! :)

**Comment by johanmalm** [comment]
Thanks @Joshua-Ashton 
Yes, starting mako helps :smile:
I thought I had sorted it with `systemctl enable mako`, but obviously not.
