### ISSUE TITLE
[Question] Where do minimized windows go?

### ISSUE THREAD

**Issue by ofiala-a51** [johanmalm/labwc#8]
This is really just a question, but I haven't figured out where the minimized windows go? Is this an unfinished feature and they go to void, or is there any toolbar that is currently supported by labwc? Sorry for spamming the issues with this.

**Comment by johanmalm** [comment]
We use the variable [view->mapped](https://github.com/johanmalm/labwc/blob/master/include/labwc.h#L170) to decide whether or not to render a view. See [https://github.com/johanmalm/labwc/blob/master/src/output.c#L350](https://github.com/johanmalm/labwc/blob/master/src/output.c#L350)
That's it really. When you click the minimize (iconify) button, we set view->mapped = false
We intend to support the foreign-toplevel protocol which enables panels to control toplevel views (see README.md)

**Comment by johanmalm** [comment]
Sorry, forgot to say, you can alt-tab to get any minimized window back.
